In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# read the data
df = pd.read_csv('/content/drive/MyDrive/Hamoye/energydata_complete.csv')
df.shape

(19735, 29)

In [3]:
df.head()

date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0  2016-01-11 17:00:00          60      30  ...        5.3  13.275433  13.275433
1  2016-01-11 17:10:00          60      30  ...        5.2  18.606195  18.606195
2  2016-01-11 17:20:00          50      30  ...        5.1  28.642668  28.642668
3  2016-01-11 17:30:00          50      40  ...        5.0  45.410389  45.410389
4  2016-01-11 17:40:00          60      40  ...        4.9  10.084097  10.084097

[5 rows x 29 columns]

In [4]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [5]:
# check null values
obj  = df.isnull().sum()
for key,value in obj.iteritems():
    print(key,",",value)

date , 0
Appliances , 0
lights , 0
T1 , 0
RH_1 , 0
T2 , 0
RH_2 , 0
T3 , 0
RH_3 , 0
T4 , 0
RH_4 , 0
T5 , 0
RH_5 , 0
T6 , 0
RH_6 , 0
T7 , 0
RH_7 , 0
T8 , 0
RH_8 , 0
T9 , 0
RH_9 , 0
T_out , 0
Press_mm_hg , 0
RH_out , 0
Windspeed , 0
Visibility , 0
Tdewpoint , 0
rv1 , 0
rv2 , 0


In [6]:
X = df.iloc[:,5].values
y = df.iloc[:,13].values

In [7]:
X = X.reshape(-1,1)

In [8]:
y = y.reshape(-1,1)

In [9]:
y

array([[ 7.02666667],
       [ 6.83333333],
       [ 6.56      ],
       ...,
       [23.62666667],
       [22.43333333],
       [21.02666667]])

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [11]:

from sklearn.metrics import r2_score
r2 = r2_score(X,y)
print('r2 score for perfect model is', round(r2,2))

r2 score for perfect model is -35.39


Q13

In [12]:
new_data = df.copy()
new_data.drop(['date', 'lights'], axis='columns', inplace=True)

In [13]:
new_data.head()

Appliances     T1       RH_1  ...  Tdewpoint        rv1        rv2
0          60  19.89  47.596667  ...        5.3  13.275433  13.275433
1          60  19.89  46.693333  ...        5.2  18.606195  18.606195
2          50  19.89  46.300000  ...        5.1  28.642668  28.642668
3          50  19.89  46.066667  ...        5.0  45.410389  45.410389
4          60  19.89  46.333333  ...        4.9  10.084097  10.084097

[5 rows x 27 columns]

In [14]:
new_data.columns

Index(['Appliances', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [15]:
new_X =  new_data.iloc[:,1:].values
new_y =  new_data.iloc[:,0].values

In [16]:
new_X.shape

(19735, 26)

In [17]:
new_y.shape

(19735,)

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_X, new_y, test_size = 0.3, random_state = 42)

In [19]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = regressor.predict(X_test)

In [22]:
from sklearn.metrics import mean_absolute_error
round(mean_absolute_error(y_test,y_pred),2)

53.64

In [23]:
rss = np.sum(np.square(y_test - y_pred))
round(rss, 2)

51918501.21

In [24]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test,  y_pred))
round(rmse, 3) 

93.64

In [25]:

r2_score = r2_score(y_test, y_pred)
round(r2_score, 2)

0.15

In [26]:
regressor.coef_

array([  -3.51072478,  495.52601962, -252.710373  , -469.52136238,
        310.97103712,  102.77165244,   31.00966845,   27.31182902,
        -16.75282177,   17.03563561,  252.71692835,   40.7120577 ,
         11.00293428,  -47.56355153,  109.13469841, -168.62716102,
       -203.23662712,  -42.58633878, -344.3898449 ,    7.31524276,
        -83.1075989 ,   31.22594824,   13.16807161,  125.43063708,
          0.82386956,    0.82386956])

In [ ]:
np.amin(regressor.coef_, axis=None, out=None)

In [31]:
np.amax(regressor.coef_, axis=None, out=None)

495.52601961887746

In [ ]:
new_data.head()

In [34]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(X_train, y_train)


Ridge(alpha=0.4)

In [35]:
y_ridge_pred = ridge_reg.predict(X_test)

In [36]:

rmse_ridge = np.sqrt(mean_squared_error(y_test, y_ridge_pred))
round(rmse_ridge, 3) 

93.66

In [38]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)
y_lasso_pred = lasso_reg.predict(X_test)
rmse_lasso = np.sqrt(mean_squared_error(y_test, y_lasso_pred))
round(rmse_lasso, 3) 

93.641

In [39]:
lasso_reg.coef_

array([-4.05585856e+00,  4.94326194e+02, -2.49638653e+02, -4.65821050e+02,
        3.10200156e+02,  1.02172472e+02,  3.03442054e+01,  2.65605806e+01,
       -1.71130125e+01,  1.70135558e+01,  2.49833620e+02,  4.00909631e+01,
        1.03049176e+01, -4.72096100e+01,  1.08879691e+02, -1.68697937e+02,
       -2.02480809e+02, -4.24460529e+01, -3.32573565e+02,  7.28122335e+00,
       -7.79887791e+01,  3.13880250e+01,  1.30781313e+01,  1.18062594e+02,
        1.63099462e+00,  3.77752618e-15])